# Generated by Django 5.1.4 on 2024-12-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_options_remove_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='emotion',
            field=models.CharField(choices=[('disgust', 'Disgust'), ('fear', 'Fear'), ('happiness', 'Happiness'), ('sadness', 'Sadness'), ('anger', 'Anger'), ('neutral', 'Neutral'), ('surprise', 'Surprise')], default='neutral', max_length=20),
        ),
    ]
